@PORT = 3000

@HOST = http://127.0.0.1:{{PORT}}

@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTkyNDU5MDAsImlkIjoxMDMsInVzZXJuYW1lIjoiZW1pbGlvY2hlY2EiLCJuYW1lIjoiRW1pbGlvIiwiaWF0IjoxNzE4MDM2MzAwfQ.OsjOEqKKpN83SpFUmI9I1ys4fYoUlsiZCbg08sybqOw


### PETICIONES INVITATIONS:

### GET ALL:
GET {{HOST}}/api/invitations
Authorization : {{TOKEN}}

### GET BY ID:
GET {{HOST}}/api/invitations/1
Authorization : {{TOKEN}}

### GET PENDING INVITATIONS BY GROUP AND USER:
GET {{HOST}}/api/invitations/bygroupanduser/13/2
Authorization : {{TOKEN}}

### CREATE INVITATION
POST {{HOST}}/api/invitations
Authorization : {{TOKEN}}
Content-Type: application/json

{
    "group_id": 12,
    "user_id": 112,
    "message": "Hola, acepta mi invitacion"

}

### ACCEPT INVITATION:
PUT {{HOST}}/api/invitations/8/accept
Authorization : {{TOKEN}}
Content-Type: application/json

{
    "user_id": 7,
    "accepted": 1
}

### REJECT INVITATION:
PUT {{HOST}}/api/invitations/1/reject
Authorization : {{TOKEN}}
Content-Type: application/json

{
    "user_id": 3,
    "accepted": 0
}

### DELETE INVITATION:
DELETE {{HOST}}/api/invitations/13
Authorization : {{TOKEN}}
