
@PORT = 3000

@HOST = http://127.0.0.1:{{PORT}}

@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTc5ODk1OTQsImlkIjoxMDYsInVzZXJuYW1lIjoibWlrX2NlcnZhbnRlcyIsIm5hbWUiOiJNaWd1ZWwiLCJpYXQiOjE3MTY3Nzk5OTR9.TKCHSfm3vBtnon11gimBRODdEqr02Z9xmDfXDHTv8aY


### Expenses ##################################################################################################

###
## Buscar expense por id
## param1: idexpense
GET {{HOST}}/api/expenses/54
Authorization : {{TOKEN}}

###
## Crear gasto asociado a un grupo y un pagador
POST {{HOST}}/api/expenses/
Authorization : {{TOKEN}}
Content-Type: application/json

{
    "group_id": "11",
    "description": "Gasto de prueba",
    "amount": "13.33",
    "date": "2033-12-31 11:11:11",
    "payer_user_id": "2",
    "active": "1"
}

###
## Editar un gasto
PUT {{HOST}}/api/expenses/52
PUT {{HOST}}/api/expenses/53
Authorization : {{TOKEN}}
Content-Type: application/json

{
    "group_id": "11",
    "description": "Gasto de prueba MODIFICADO",
    "amount": "13.33",
    "date": "2033-12-31 11:11:11",
    "payer_user_id": "2",
    "active": "1"
}

###
## Desactivar un gasto

###
## Eliminar un gasto
DELETE  {{HOST}}/api/expenses/52
Authorization : {{TOKEN}}
DELETE  {{HOST}}/api/expenses/53
Authorization : {{TOKEN}}


### Peticiones relacionadas por grupos

## Buscar todos los gastos de un usuario en un grupo ordenados por fecha y que esten activos
## param1:idGroup, param2: idUser
GET {{HOST}}/api/expenses/bygroup/byuser/actives/11/2
Authorization : {{TOKEN}}

###
## Buscar todos los gastos Activos de un grupo
## param1: idGroup
GET {{HOST}}/api/expenses/bygroup/actives/3
Authorization : {{TOKEN}}

###
## Buscar todos los gastos Activos y no activos de un grupo
## param1: idGroup
GET {{HOST}}/api/expenses/bygroup/all/11
Authorization : {{TOKEN}}

###
## Buscar el total de los gastos Activos de un grupo por usuario
## param1: idGroup
GET {{HOST}}/api/expenses/bygroup/actives/totalexpensesbyuser/3
Authorization : {{TOKEN}}