@PORT = 3000

@HOST = http://127.0.0.1:{{PORT}}

@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTg0NTAzNDgsImlkIjoxMDQsInVzZXJuYW1lIjoic2NhbmZlcmxhX3lhaCIsIm5hbWUiOiJHb255YWgiLCJpYXQiOjE3MTgzNjM5NDh9.rboCp9tkZTu5lN5wzgkDjKN-hht9U0i5-3c8iD9lbTk


### PETICIONES INVITATIONS:

### GET ALL:
GET {{HOST}}/api/invitations
Authorization : {{TOKEN}}

### GET BY ID:
GET {{HOST}}/api/invitations/1
Authorization : {{TOKEN}}

### GET INVITATIONS BY USER:
GET {{HOST}}/api/invitations/byuser/2
Authorization : {{TOKEN}}

### GET PENDING INVITATIONS BY GROUP AND USER:
GET {{HOST}}/api/invitations/bygroupanduser/13/2
Authorization : {{TOKEN}}

### CREATE INVITATION
POST {{HOST}}/api/invitations
Authorization : {{TOKEN}}
Content-Type: application/json

{
    "group_id": 20,
    "user_id": 18,
    "message": "Hola, acepta mi invitacion"

}

### ACCEPT/REJECT INVITATION:
PUT {{HOST}}/api/invitations/34/accept
Authorization : {{TOKEN}}
Content-Type: application/json

{
    "user_id": 18
}

### DELETE INVITATION:
DELETE {{HOST}}/api/invitations/5
Authorization : {{TOKEN}}
