
@PORT = 3000

@HOST = http://127.0.0.1:{{PORT}}

@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTc5ODk1OTQsImlkIjoxMDYsInVzZXJuYW1lIjoibWlrX2NlcnZhbnRlcyIsIm5hbWUiOiJNaWd1ZWwiLCJpYXQiOjE3MTY3Nzk5OTR9.TKCHSfm3vBtnon11gimBRODdEqr02Z9xmDfXDHTv8aY


###
## Crear email
POST {{HOST}}/api/mails/
Authorization : {{TOKEN}}
Content-Type: application/json

{
    "to": "anuarkhan@gmail.com",
    "subject": "Email de registro",
    "html": "<h2>Hola caracola</h2> <p>Esto es un <strong>parrafo</strong></p>"
}

