
@PORT = 3000

@HOST = http://127.0.0.1:{{PORT}}

@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTk0Njc0NTIsImlkIjoxMTAsInVzZXJuYW1lIjoiZ29uIiwibmFtZSI6IkdvbiIsImlhdCI6MTcxODI1Nzg1Mn0.n8CCAPJ43vPKGX44XIiQL1zR2z8WcahG28PislaVsmU

### Login
POST {{HOST}}/api/login
Content-Type: application/json

{
    "mail": "gonzalo.scanferla@gmail.com",
    "password" : "12345",
    "rememberMe" : true
}

### Verify Token
GET {{HOST}}/api/login/{{TOKEN}}


### GetAll
GET {{HOST}}/api/users
Authorization : {{TOKEN}}

### GetById
GET {{HOST}}/api/users/98
Authorization : {{TOKEN}}

### GetByUsername
GET {{HOST}}/api/users/byusername/blavens2o
Authorization : {{TOKEN}}

### Get Filtered Usernames
GET {{HOST}}/api/users/filteredusernames/mi
Authorization : {{TOKEN}}

### Create (register)
POST {{HOST}}/api/register
Content-Type: application/json

//mail, username, password, firstname, lastname, phone, image
{
    "mail": "g_scanferla@yahoo.it",
    "username": "scanferla_yah",
    "password": "123456",
    "firstname": "Gonyah",
    "lastname": "Yahferla",
    "phone": "123456789",
    "image": ""
}

### Update user

PUT {{HOST}}/api/users/update
Authorization : {{TOKEN}}
Content-Type: application/json

//mail, username, password, firstname, lastname, phone, image
{
    "mail": "bart_simpson@springfieldmail.com",
    "username": "john.doe",
    "password": "12345",
    "firstname": "John",
    "lastname": "Doe",
    "phone": "123 456 789",
    "image": ""
}

### Update password

PUT {{HOST}}/api/users/updatePwd
Authorization : {{TOKEN}}
Content-Type: application/json

//password
{
    "password": "12345"
}

###

DELETE {{HOST}}/api/users/4
Authorization : {{TOKEN}}

####
GET {{HOST}}/api/users/members/bygroup/3
Authorization : {{TOKEN}}