@PORT = 3000

@HOST = http://127.0.0.1:{{PORT}}


@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTg0NTAzNDgsImlkIjoxMDQsInVzZXJuYW1lIjoic2NhbmZlcmxhX3lhaCIsIm5hbWUiOiJHb255YWgiLCJpYXQiOjE3MTgzNjM5NDh9.rboCp9tkZTu5lN5wzgkDjKN-hht9U0i5-3c8iD9lbTk


### PETICIONES GROUPS:

### GET ALL:
GET {{HOST}}/api/groups
Authorization : {{TOKEN}}

### GET BY ID:
GET {{HOST}}/api/groups/11
Authorization : {{TOKEN}}

### CREATE NEW GROUP
POST {{HOST}}/api/groups
Authorization : {{TOKEN}}
Content-Type: application/json

{
     
    "description": "Cena de empresa Lorena 2",
    "category_id": 1
}

### UPDATE GROUP
PUT {{HOST}}/api/groups/21
Authorization : {{TOKEN}}
Content-Type: application/json

{
    "description": "Comida de empresa",
    "category_id": 2
}

### DELETE GROUP
DELETE {{HOST}}/api/groups/13
Authorization : {{TOKEN}}




###
## Obtiene los roles de todos los grupos del usuario con idUser (1 en este caso)
## param1: idUser
GET {{HOST}}/api/groups/roles
Authorization : {{TOKEN}}

###
GET {{HOST}}/api/groups/getallbyuser
Authorization : {{TOKEN}}