GET http://localhost:3000/api/users

###

POST http://localhost:3000/api/users
Content-Type: application/json

//mail, username, password, firstname, lastname, phone, image
{
    "mail": "john.doe@mail.com",
    "username": "john.doe",
    "password": "123456",
    "firstname": "John",
    "lastname": "Doe",
    "phone": "123456789",
    "image": ""
}

###

PUT http://localhost:3000/api/users/4
Content-Type: application/json

//mail, username, password, firstname, lastname, phone, image
{
    "mail": "john.doe@mail.com",
    "username": "john.doe",
    "password": "000000",
    "firstname": "John",
    "lastname": "Doe",
    "phone": "123 456 789",
    "image": ""
}

###

DELETE http://localhost:3000/api/users/4
