@PORT = 3000

@HOST = http://127.0.0.1:{{PORT}}

@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTc5ODk1OTQsImlkIjoxMDYsInVzZXJuYW1lIjoibWlrX2NlcnZhbnRlcyIsIm5hbWUiOiJNaWd1ZWwiLCJpYXQiOjE3MTY3Nzk5OTR9.TKCHSfm3vBtnon11gimBRODdEqr02Z9xmDfXDHTv8aY


### PETICIONES GROUPS:

### GET ALL:
GET {{HOST}}/api/groups
Authorization : {{TOKEN}}

### GET BY ID:
GET {{HOST}}/api/groups/11
Authorization : {{TOKEN}}

### CREATE NEW GROUP
POST {{HOST}}/api/groups
Authorization : {{TOKEN}}
Content-Type: application/json

{
    "name" : "Fiesta de fin de año",
    "description": "Cena de fin de año en 'Restaurante El Buen Sabor'",
    "category": 1
}

### UPDATE GROUP
PUT {{HOST}}/api/groups/11
Authorization : {{TOKEN}}
Content-Type: application/json

{
    "name" : "Viaje de fin de curso",
    "category": 2
}

### DELETE GROUP
DELETE {{HOST}}/api/groups/11
Authorization : {{TOKEN}}
