
@PORT = 3000

@HOST = http://127.0.0.1:{{PORT}}

@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTgyOTg5OTYsImlkIjoxMDIsInVzZXJuYW1lIjoicGVwaXRvcGVyZXoiLCJuYW1lIjoiUGVwaXRvIiwiaWF0IjoxNzE3MDg5Mzk2fQ.gy8JYt1cHytgXOEfC-6WRkf8pl3ghC4-1Vztib7NSU4

### Login
POST {{HOST}}/api/login
Content-Type: application/json

{
    "mail": "pepito.perez@gmail.com",
    "password" : "123456",
    "rememberMe" : true
}

### Verify Token
GET {{HOST}}/api/login/{{TOKEN}}


### GetAll
GET {{HOST}}/api/users
Authorization : {{TOKEN}}

### GetById
GET {{HOST}}/api/users/98
Authorization : {{TOKEN}}

### Create (register)
POST {{HOST}}/api/register
Content-Type: application/json

//mail, username, password, firstname, lastname, phone, image
{
    "mail": "miguelon_1547@pigeonmail.com",
    "username": "mik_cervantes",
    "password": "123456",
    "firstname": "Miguel",
    "lastname": "De Cervantes Saavedra",
    "phone": "123456789",
    "image": ""
}

###

PUT {{HOST}}/api/users/4
Authorization : {{TOKEN}}
Content-Type: application/json

//mail, username, password, firstname, lastname, phone, image
{
    "mail": "freddie@mail.com",
    "username": "john.doe",
    "password": "12345",
    "firstname": "John",
    "lastname": "Doe",
    "phone": "123 456 789",
    "image": ""
}

###

DELETE {{HOST}}/api/users/4
Authorization : {{TOKEN}}
