GET http://localhost:3000/api/users

###

POST http://localhost:3000/api/users
Content-Type: application/json

//mail, username, password, firstname, lastname, phone, image
{
    "mail": "john.doe@mail.com",
    "username": "john.doe",
    "password": "123456",
    "firstname": "John",
    "lastname": "Doe",
    "phone": "123456789",
    "image": ""
}

###

PUT http://localhost:3000/api/users/4
Content-Type: application/json

//mail, username, password, firstname, lastname, phone, image
{
    "mail": "john.doe@mail.com",
    "username": "john.doe",
    "password": "000000",
    "firstname": "John",
    "lastname": "Doe",
    "phone": "123 456 789",
    "image": ""
}

###

DELETE http://localhost:3000/api/users/4


### Expenses ##################################################################################################

## Buscar todos los gastos de un usuario en un grupo ordenados por fecha y que esten activos
## param1:idGroup, param2: idUser
GET http://localhost:3000/api/expenses/bygroup/byuser/actives/11/2

###
## Buscar todos los gastos Activos de un grupo
## param1: idGroup
GET http://localhost:3000/api/expenses/bygroup/actives/11

###
## Buscar todos los gastos Activos y no activos de un grupo
## param1: idGroup
GET http://localhost:3000/api/expenses/bygroup/all/11

###
## Buscar gasto por id
GET http://localhost:3000/api/expenses/3

###
## Crear gasto asociado a un grupo y un pagador
POST http://localhost:3000/api/expenses/
Content-Type: application/json

{
    "group_id": "11",
    "description": "Gasto de prueba",
    "amount": "13.33",
    "date": "2033-12-31",
    "payer_user_id": "2",
    "active": "1"
}

###
## Editar un gasto
PUT http://localhost:3000/api/expenses/52
Content-Type: application/json

{
    "group_id": "11",
    "description": "Gasto de prueba MODIFICADO nuevamente",
    "amount": "13.33",
    "date": "2033-12-31",
    "payer_user_id": "2",
    "active": "1"
}

###
## Desactivar un gasto

###
## Eliminar un gasto
DELETE  http://localhost:3000/api/expenses/52



### Pagos: en progreso
###
GET http://localhost:3000/api/expenses/payments/1