@PORT = 3000

@HOST = http://127.0.0.1:{{PORT}}


@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTg5NjQzNTksImlkIjoxMDIsInVzZXJuYW1lIjoiYW51YXJraGFuIiwibmFtZSI6IkFudWFyIiwiaWF0IjoxNzE3NzU0NzU5fQ.SL5W98p4OIGUKLKP-lRPse7-QYL_rKWYZob2OICN21s


### PETICIONES GROUPS:

### GET ALL:
GET {{HOST}}/api/groups
Authorization : {{TOKEN}}

### GET BY ID:
GET {{HOST}}/api/groups/11
Authorization : {{TOKEN}}

### CREATE NEW GROUP
POST {{HOST}}/api/groups
Authorization : {{TOKEN}}
Content-Type: application/json

{
     
    "description": "Cena de empresa Anuar",
    "category_id": 1
}

### UPDATE GROUP
PUT {{HOST}}/api/groups/21
Authorization : {{TOKEN}}
Content-Type: application/json

{
    "description": "Comida de empresa",
    "category_id": 2
}

### DELETE GROUP
DELETE {{HOST}}/api/groups/13
Authorization : {{TOKEN}}




###
## Obtiene los roles de todos los grupos del usuario con idUser (1 en este caso)
## param1: idUser
GET {{HOST}}/api/groups/roles
Authorization : {{TOKEN}}

###
GET {{HOST}}/api/groups/getallbyuser
Authorization : {{TOKEN}}